### ISSUE TITLE
Revise a number of styles in WSM stylesheet

### ISSUE THREAD

**Issue by wsmagazine** [washingtonstateuniversity/magazine.wsu.edu#126]
Need to include in stylesheet:
.summer {color: #c69214;}

All other season color classes seem to be in place.

**Comment by philcable** [comment]
@wsmagazine There's an extra trailing comma in the current stylesheet which makes the rule invalid. This is fixed in the newest version (https://github.com/washingtonstateuniversity/magazine.wsu.edu/blob/master/style.css#L1386-L1389), which we'll deploy soon!

The color is slightly different than what you have here, though - would you like that changed?

**Comment by wsmagazine** [comment]
Actually there are several color changes that John pointed out. I'll get the revised styles to you.

**Comment by wsmagazine** [comment]
Here are the color and other styles that need to be changed in WSM stylesheet. Thanks!
[wsm-styles-to-change-July2016.txt](https://github.com/washingtonstateuniversity/magazine.wsu.edu/files/358172/wsm-styles-to-change-July2016.txt)
